### ISSUE TITLE
Multiblock can be added many times

### ISSUE THREAD

**Issue by cdipe** [catalyst/moodle-block_multiblock#100]
Multiblock can be added multiple times in the same course and/or category.

- When having been added to a course, Multiblock should not be selectable when adding new block to the course
- When having been added on category level and set to show in all courses in that category, Multiblock should not be selectable when adding new block to the same category OR to courses in that category

Using Moodle 4.1 and Multiblock 1.3.6 (2023012500)

**Comment by danmarsden** [comment]
Can you explain why? We have several pages in different client sites that have multiple multi block blocks on  the same page. It's intentional that you can add multiple multi blocks to the same page - just like the text/html block allows.

**Comment by cdipe** [comment]
Hi @danmarsden, I could only define one Multiblock in the Moodle Administration - but now I see that it's possible to create 
 / re-define them locally in courses and categories as well! Sorry about that!

**Comment by danmarsden** [comment]
all good! - thanks.
