### ISSUE TITLE
Clarity on block_multiblock | subblock setting

### ISSUE THREAD

**Issue by jprovasnik** [catalyst/moodle-block_multiblock#106]
Version: 1.3.6 (2023012500)
Moodle 4.1 Workplace and Moodle 4.2 Workplace

In the admin settings for Multi block, there is a setting for "Multiblock - Subblocks / block_multiblock | subblock". I dont see in the read me what this setting is for - could clarity be provided? On the Site Admin Multiblock settings page, all it says is "how" to interact with that setting (it says "Multiple blocks can be selected") but it doesn't say "what" the setting is for. 

For example:
• When "nothing" is selected inside the "Multiblock - Subblocks" Admin setting, then when I manage an existing MultiBlock I can see a certain # of blocks available to select in the 'Add a new sub-block" setting.
• When "all" items are selected inside the "Multiblock - Subblocks" Admin setting, then when I managing an existing MultiBlock I can still see that same # of blocks available to select in the 'Add a new sub-block" setting.

So I wasn't sure if this was a bug or not that both values (all selected or none selected) yield the same result, but wanted to see if more explanation could be added.

![settings](https://github.com/catalyst/moodle-block_multiblock/assets/44345287/d9b01d63-d28c-486a-8152-7870de438bf2)

**Comment by sumaiyamannan** [comment]
A fix for it is [here](https://github.com/catalyst/moodle-block_multiblock/pull/113)
