### ISSUE TITLE
Creation of dynamic property block_multiblock::$blocks is deprecated

### ISSUE THREAD

**Issue by ewallah** [catalyst/moodle-block_multiblock#109]
Using [$this->blocks](https://github.com/catalyst/moodle-block_multiblock/blob/master/block_multiblock.php#L93) without declaring a `@var array $blocks` in the class generates a deprecated error in php8.2.

Exception - Unknown error type: Creation of dynamic property block_multiblock::$blocks is deprecated in [dirroot]/blocks/multiblock/block_multiblock.php on line 93</div><div class="notifytiny">Debug info: <br />Error code: generalexceptionmessage</div><div class="notifytiny">Stack trace: <ul style="text-align: left" data-rel="backtrace"><li>line 157 of /lib/behat/lib.php: Exception thrown</li><li>line 93 of /blocks/multiblock/block_multiblock.php: call to behat_error_handler()</li><li>line 152 of /blocks/multiblock/block_multiblock.php: call to block_multiblock->load_multiblocks()</li><li>line 337 of /blocks/moodleblock.class.php: call to block_multiblock->get_content()</li><li>line 231 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()</li><li>line 215 of /blocks/multiblock/block_multiblock.php: call to block_base->get_content_for_output()</li><li>line 1231 of /lib/blocklib.php: call to block_multiblock->get_content_for_output()</li><li>line 1289 of /lib/blocklib.php: call to block_manager->create_block_contents()</li><li>line 377 of /lib/blocklib.php: call to block_manager->ensure_content_created()</li><li>line 4130 of /lib/outputrenderers.php: call to block_manager->region_has_content()</li><li>line 28 of /theme/classic/layout/columns.php: call to core_renderer->blocks()</li><li>line 1477 of /lib/outputrenderers.php: call to include()</li><li>line 1403 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()</li><li>line 290 of /course/view.php: call to core_renderer->header()</li></ul>

Adding this to the code, fixes the error:
```
    /** @var array $blocks. */
    private $blocks;

```

**Comment by danmarsden** [comment]
Thanks @ewallah - feel free to submit a PR otherwise we'll try to come back to it soon.

**Comment by danmarsden** [comment]
thanks for the PR! :-)
