### ISSUE TITLE
Tab borders go away when there are too many tabs.

### ISSUE THREAD

**Issue by peterspicer-catalyst** [catalyst/moodle-block_multiblock#21]
Reported by Jakub.

Tab borders go away when there are too many tabs.

![image](https://user-images.githubusercontent.com/30900984/71252673-8d4ed900-231d-11ea-8ac2-246ecc2c9676.png)

**Comment by Arantor** [comment]
This isn't something that is fixable inside Multiblock; it's a thing that happens inside the markup with Bootstrap itself and can happen in any context where Bootstrap 4 is being used.
