### ISSUE TITLE
Course link/title displayed in breadcrumb when managing Multiblock content is wrong

### ISSUE THREAD

**Issue by rolandsherwood2** [catalyst/moodle-block_multiblock#59]
Hi. Many thanks for this excellent plugin. I just wanted to report a bug which results in the wrong course link/title being displayed when managing a Multiblock's content:

<img width="533" alt="Screen Shot 2020-05-31 at 11 14 27" src="https://user-images.githubusercontent.com/36252128/83344018-581ace00-a334-11ea-9679-37ca9e1d4eeb.png">

The above shows the location of the Mutliblock in course 'Testing module', but when clicking the Mutliblock's 'Manage content' link...

<img width="651" alt="Screen Shot 2020-05-31 at 11 14 41" src="https://user-images.githubusercontent.com/36252128/83344019-5d781880-a334-11ea-84d2-39f3a1fabbeb.png">

...a completely different course/title is displayed in the breadcrumb trail.

We think this could potentially be quite confusing for teachers who rely on being able to click the course link in the breadcrumb trail in order to return to the course page they were working in.

Thanks again for your efforts and for sharing this plugin.

**Comment by Arantor** [comment]
This is an interesting one, I'd seen it on a heavily modified Totara, where a completely unrelated course would be shown (and where I'd chalked it up to some unrelated modifications that that Totara has)

Completely agree that this is confusing, though it is a display issue and not a data integrity one. Will see if I can solve it sometime, though as you can imagine I'm currently doing prep for major summer development work and getting ready for a much larger autumn rollout than I'd normally be doing (as CV-19 is still causing a lot of concerns here in the UK), but if I get a chance I will look at it again.

**Comment by Arantor** [comment]
Also, I'd be interested to know what version of Moodle, what other plugins you're using (beyond core) and are you putting this in an activity or a course page?

**Comment by rolandsherwood2** [comment]
Many thanks for looking into this - and it is indeed a weird one! Just to confirm we're using Multiblock under Moodle 3.7.5, with the block added to a course page. Re. additional plugins: we use more than a hundred, so if that is the cause I'm not sure where exactly to start looking. Alternatively, and as soon as I have some time, I'll try to test on a fresh instance to see how it behaves there.

Thanks again.

**Comment by Arantor** [comment]
I did some more digging this evening and I think I found a solution - I've committed it with the intent of it being 1.3.0 'real soon' but if you wanted to grab the code for it ahead of it being merged, please do - it's in the additional-styles branch along with new styles for 3-column and a carousel layout.
