### ISSUE TITLE
Add behat support for non boost themes

### ISSUE THREAD

**Issue by iplusacademy** [catalyst/moodle-block_multiblock#73]
The lines 

```
    # The usual 'And I add "Multiblock" block' step can fail in JS with lots of blocks present.
    And I select "Add a block" from flat navigation drawer
    And I click on "Multiblock" "link"

```
are not necesary and can be replaced by the default method to create a block.

`    And I add the "Multiblock" block
`

This way, non boost based themes without a navigation drawer can also be tested.  I did the changes with a classic based theme, and all tests pass.

**Comment by danmarsden** [comment]
behat steps updated along these lines in #87 - thanks!
