### ISSUE TITLE
Add nav breadcrumb to manage.php to take user to the page where the block is located.

### ISSUE THREAD

**Issue by andrewmadden** [catalyst/moodle-block_multiblock#74]
Currently, there does not seem to be a simple way to return to the dashboard and course from the manage page for a multiblock. I propose adding an extra nav breadcrumb to take the user back to the page calculated as the `$actualpageurl` in `\block_multiblock\helper::bootstrap_page()`

**Comment by danmarsden** [comment]
this was merged ages ago... someone forgot to close this off, doing it now :-)
