### ISSUE TITLE
Move this block into catalyst/ org git repo space

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-block_multiblock#77]
@Arantor do you have any objection to this? We are getting more traction on this in a few places and this will make it a bit simpler for everyone. Still happy to run with whatever workflow you prefer for reviews etc so you're still the maintainer

**Comment by brendanheywood** [comment]
hi Peter, do you have any thoughts on the AU team adopting this plugin? Our fork has moved along a bit and this repo hasn't seen any commits in almost a year and we'd like to get the plugins directory updated.

**Comment by Arantor** [comment]
I no longer work for Catalyst so I’m perfectly fine with whatever adoption you want to do.

**Comment by brendanheywood** [comment]
thanks heaps Peter :)

Ok my proposed housekeeping tasks:

1) Do you want to add in a chunk of text to the readme with whatever credits / bio for yourself and I'll make sure that is retained?

2) For the github repository the ideal end state is that we retain all of the github metadata around issues and pull request history and to do this the best way is the transfer ownership of the repo. If you are happy with this approach then I'm happy to do all the legwork if you can assign me as an admin to this repo. I'll sort syncing back all the code then delete our fork and make this repo replace it.

3a) For the plugins directory at the moment the primary maintainer is you and the shared catalyst user is second. I propose to just swap them so you are still listed as the maintainer but it means the catalyst account can manage the other users. If you are happy with that then we'll ask HQ to swap that as neither of us can do it directly and I'll point them at this thread for the 'adoption papers'.

OR

3b) If you no longer want to be a maintainer I can instead list you under the Contributors section under a label of your choosing such as 'Original Maintainer' ?

thanks for the quick reply

**Comment by brendanheywood** [comment]
hi @Arantor just following up again. Are you ok with this plan? The alternative is fully fork and break the github magic linkage between this repo and what will become the new fork, which means we'll lose all the repo metadata, issues and pull requests etc. It's much better for the community to have a smoother transfer of maintainers rather than split forks.

**Comment by Arantor** [comment]
Sorry I didn’t reply, been a bit busy.

Honestly, I’m good with whatever you want to do - I’m not going to be maintaining this going forward unless something very strange happens that causes me to return to Catalyst (unlikely, to be honest), so whatever works for you is more important than anything else.

**Comment by brendanheywood** [comment]
Ok cool, well the easiest is if you can grant me admin access to this repo and I'll transfer it over

**Comment by brendanheywood** [comment]
Thanks, I've accepted that invite but I think it was just the maintainer role and I'll need full admin to transfer it, eg I can't see the settings tab

**Comment by Arantor** [comment]
I don’t see where to change it to admin, guess the quickest way is just to transfer the repo to you?

**Comment by brendanheywood** [comment]
It should be here:

https://github.com/Arantor/moodle-block_multiblock/settings/access

Under Role -> Admin

**Comment by Arantor** [comment]
It’s not an organisation repo, setting admin isn’t an option, only collaborator. I’d transfer it to you but there’s also a repo in your account with this name.

**Comment by brendanheywood** [comment]
ok, I've just renamed mine and I'll delete it later, please try again

**Comment by Arantor** [comment]
Now it says: brendanheywood already has a repository in the Arantor/moodle-block_multiblock network

It feels like GitHub is giving me a message that I shouldn’t give this away…!

**Comment by brendanheywood** [comment]
Ok :)

I've just deleted mine completely now, lets give it another whirl...

**Comment by Arantor** [comment]
Apparently it’s been requested, so I guess you’ll be good to go now… have fun :)

**Comment by brendanheywood** [comment]
Woohooo we have liftoff! thanks for all your perseverance

**Comment by Arantor** [comment]
Glad to be of service :)
