### ISSUE TITLE
issue with block manager plugin

### ISSUE THREAD

**Issue by mnods** [catalyst/moodle-block_multiblock#78]
hi, while you're on this, perhaps you could take a look at https://github.com/catalyst/moodle_tool_blocksmanager/issues/18 - cheers

**Comment by danmarsden** [comment]
yeah - it's not a bug with multiblock but an issue with blocksmanager - there's a PR here that needs testing:
https://github.com/catalyst/moodle_tool_blocksmanager/issues/18
