### ISSUE TITLE
Loosing activities - restored course

### ISSUE THREAD

**Issue by avodan** [catalyst/moodle-block_multiblock#79]
Hi!
We are almost loosing all the progression bars inside the multiblock (dropdown) when we restore a course. There is only 1 progression bar that remains in the multiblock. Moodle : 3.10 / Fordson : 3.10 / Multiblock : 3.9
Thank you

Daniel

**Comment by danmarsden** [comment]
I think this is probably due to #64 - it would be good if you could try to reproduce this with the latest code, and if it's still an issue provide a bit more information? - I'm not sure what "progression bars" are - is that a block you have inside the multi-block?
