### ISSUE TITLE
Weird behavior on 4.0.2

### ISSUE THREAD

**Issue by jimenez-b** [catalyst/moodle-block_multiblock#82]
While testing on a 4.0.2 installation, we found an interesting behavior:

1. Go to personal Dashboard.
2. Turn editing on.
3. Select Add a block.
4. Select Multiblock.
5. Select Actions menu (gear icon) and then select Configure Multiblock block.
6. Go to Multiblock presentation style menu and select Columns: 2 equal.
7. Select Save changes.

Result: Only the Split and delete block option is displayed in the Actions menu.

Apparently, it only happens with the columns options, not the tab options

**Comment by michaelkotlyar** [comment]
Added a [PR](https://github.com/catalyst/moodle-block_multiblock/pull/89) for this

**Comment by danmarsden** [comment]
thanks @uzimike - merged.
