### ISSUE TITLE
Moodle 3.11 - Error when "Turn editing on"

### ISSUE THREAD

**Issue by hannibal9smith** [catalyst/moodle-block_multiblock#83]
**Error Message:**
Exception - Argument 2 passed to tool_blocksmanager\locking_manager::can_move() must be of the type string, null given, called in [dirroot]/admin/tool/blocksmanager/classes/block_manager.php on line 366

Moodle updated from 3.9 to 3.11. Could the DB type be the issue?

**Comment by danmarsden** [comment]
that's an issue with the blocksmanager plugin - more details on that here:
https://github.com/catalyst/moodle_tool_blocksmanager/issues/18
