### ISSUE TITLE
Moodle 4 compatibility

### ISSUE THREAD

**Issue by sharpchi** [catalyst/moodle-block_multiblock#84]
I've just run the behat tests on Moodle 4.0.3 and get the following errors:
--- Failed scenarios:
    /var/www/html/blocks/multiblock/tests/behat/accordion.feature:7
    /var/www/html/blocks/multiblock/tests/behat/basic_test.feature:7
    /var/www/html/blocks/multiblock/tests/behat/defaultsettings.feature:27
    /var/www/html/blocks/multiblock/tests/behat/dropdown.feature:7
    /var/www/html/blocks/multiblock/tests/behat/merging_blocks.feature:7
    /var/www/html/blocks/multiblock/tests/behat/tabbed.feature:7
    /var/www/html/blocks/multiblock/tests/behat/tabbed_vertical_left.feature:7
    /var/www/html/blocks/multiblock/tests/behat/tabbed_vertical_right.feature:7

The errors either relate to the "Customise this page" button not existing, or with regards to adding the block from the flat navigation

**Comment by danmarsden** [comment]
Thanks Mark - pull requests always welcome :-)

**Comment by michaelkotlyar** [comment]
I've made a PR [here](https://github.com/catalyst/moodle-block_multiblock/pull/87). There were also failures with the HTML block now being renamed as the Text block.
