### ISSUE TITLE
Deleting or Editing Multiblock

### ISSUE THREAD

**Issue by DrVictoriaD** [catalyst/moodle-block_multiblock#98]
Is there a way to edit or delete a multiblock once it is on a page?  Also, can you add it to the course page and not just the Dashboard page... not an option - just left right or footer....I haven't seen this....

**Comment by danmarsden** [comment]
multiblock is set to allow all page types so yes, you should be able to add it to a course page. - I do think there's a css bug on the editing drop list in newer moodle versions making it "hide" the links to the delete/edit options - try switching to the classic theme to see if that helps and it might confirm there's a bug when using it in boost-based themes?

**Comment by DrVictoriaD** [comment]
Dan:
I did change to another "theme" and it does allow me to edit/delete
multiblock.  So guess there is a bug with other themes.

Also, how do I add this multiblock to the middle of the course page.  I see
a right, left, and footer option.  From the screen shots it looked like
there were tabs that were created in the middle of the screen - I want on a
course page not the dashboard page.

Thanks in advance for your help.

**Comment by DrVictoriaD** [comment]
Dan:
Is there a particular "theme" in Moodle that will allow the Multiblock to
be added to the middle of the course page?

**Comment by danmarsden** [comment]
those questions about adding blocks into course pages are probably better suited to the Moodle forums as they don't really relate to multi-block at all, but to general theme / block support - thanks!

I'm hoping to allocate a developer to look further into the bug with displaying the editing controls in Multiblock, but it may be some time before we manage to push a fix for this.

**Comment by sumaiyamannan** [comment]
@DrVictoriaD  can you tell me the moodle version and which theme were you using earlier?
Thanks

**Comment by DrVictoriaD** [comment]
We are using Moodle 3.10 version and I was using a Lambda theme.  If I
choose the boost theme I am able to edit and delete blocks.  Is there a
particular theme that works with putting the multiblock on the center of
the page?

**Comment by sumaiyamannan** [comment]
Thank you for the information. 
Sorry I am not aware of a particular theme for it.

**Comment by danmarsden** [comment]
closing this as it was a bug with a 3rd party theme (lambda) - all the best!
